In [1]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Utilities
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("reddit-cleanjokes.csv")

# Preview
df.head()

   ID                                               Joke
0   1  What did the bartender say to the jumper cable...
1   2  Don't you hate jokes about German sausage? The...
2   3  Two artists had an art contest... It ended in ...
3   4  Why did the chicken cross the playground? To g...
4   5   What gun do you use to hunt a moose? A moosecut!

In [5]:
print(df.columns.tolist())

['ID', 'Joke']

In [7]:
print(df.head())

   ID                                               Joke
0   1  What did the bartender say to the jumper cable...
1   2  Don't you hate jokes about German sausage? The...
2   3  Two artists had an art contest... It ended in ...
3   4  Why did the chicken cross the playground? To g...
4   5   What gun do you use to hunt a moose? A moosecut!

In [12]:
df.head()

   ID                                               Joke
0   1  What did the bartender say to the jumper cable...
1   2  Don't you hate jokes about German sausage? The...
2   3  Two artists had an art contest... It ended in ...
3   4  Why did the chicken cross the playground? To g...
4   5   What gun do you use to hunt a moose? A moosecut!

In [19]:
df.head()
df.columns

Index(['ID', 'Joke'], dtype='str')

In [24]:
print('y_test' in globals())
print('y_pred_rf' in globals())

False
False

In [26]:
print(hasattr(rf_model, "estimators_"))

False