In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
# Load CSV file
df = pd.read_csv('police_data.csv')

# Quick look at the data
df.head()

   case_id   stop_date stopped_at  ... is_arrested  drugs_related_stop  stopped_by
0        1  2005-08-28      01:00  ...         Yes                  No         100
1        2  2005-10-01      00:00  ...         Yes                 Yes         101
2        3  2005-10-01      00:00  ...          No                 Yes         102
3        4  2005-10-02      09:30  ...         Yes                  No         103
4        5  2005-10-03      14:00  ...          No                  No         104

[5 rows x 15 columns]

In [5]:
df.select_dtypes(include=['object', 'string'])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[3193 rows x 0 columns]

In [7]:
print(df.head())
print(df.columns)
print(df.info())

   case_id  stop_date  stopped_at  ...  is_arrested  drugs_related_stop  stopped_by
0        1          0          60  ...            1                   0         100
1        2          1           0  ...            1                   1         101
2        3          1           0  ...            0                   1         102
3        4          2         359  ...            1                   0         103
4        5          3         597  ...            0                   0         104

[5 rows x 15 columns]
Index(['case_id', 'stop_date', 'stopped_at', 'driver_gender', 'year_of_birth',
       'driver_age', 'driver_race', 'stop_duration_in_minutes', 'violation',
       'search_conducted', 'search_type', 'stop_outcome', 'is_arrested',
       'drugs_related_stop', 'stopped_by'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 3193 entries, 0 to 3192
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   case_id                   3193 non-null   int64
 1   stop_date                 3193 non-null   int64
 2   stopped_at                3193 non-null   int64
 3   driver_gender             3193 non-null   int64
 4   year_of_birth             3193 non-null   int64
 5   driver_age                3193 non-null   int64
 6   driver_race               3193 non-null   int64
 7   stop_duration_in_minutes  3193 non-null   int64
 8   violation                 3193 non-null   int64
 9   search_conducted          3193 non-null   int64
 10  search_type               3193 non-null   int64
 11  stop_outcome              3193 non-null   int64
 12  is_arrested               3193 non-null   int64
 13  drugs_related_stop        3193 non-null   int64
 14  stopped_by                3193 non-null   int64
dtypes: int64(15)
memory usage: 374.3 KB
None

In [13]:
print(df.columns.tolist())

['case_id', 'stop_date', 'stopped_at', 'driver_gender', 'year_of_birth', 'driver_age', 'driver_race', 'stop_duration_in_minutes', 'violation', 'search_conducted', 'search_type', 'stop_outcome', 'is_arrested', 'drugs_related_stop', 'stopped_by']

In [16]:
df.head()

   case_id   stop_date stopped_at  ... is_arrested  drugs_related_stop  stopped_by
0        1  2005-08-28      01:00  ...         Yes                  No         100
1        2  2005-10-01      00:00  ...         Yes                 Yes         101
2        3  2005-10-01      00:00  ...          No                 Yes         102
3        4  2005-10-02      09:30  ...         Yes                  No         103
4        5  2005-10-03      14:00  ...          No                  No         104

[5 rows x 15 columns]